version: '3'
  
services:
  result:
    image: 'who-rule-the-world-result'
    networks: 
      - "front-tier"
    entrypoint: nodemon --inspect=0.0.0.0 server.js
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - './result:/usr/local/app'
    ports:
      - "5001:80"
      - "127.0.0.1:9229:9229"

  db:
    image: postgres:15-alpine
    networks: 
      - "back-tier" 
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"

  vote:
    image: 'who-rule-the-world-vote'
    networks:
      - "front-tier"
    volumes: 
      - 'vote-data:/usr/local/app'
      - './healthchecks:/healthchecks'
    ports:
      - '5002:80'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: redis
    networks:
      - "back-tier"
    volumes:
       - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"

  worker: 
    image: 'who-rule-the-world-worker'
    networks:
      - "back-tier"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  seed-data:
    image: 'who-rule-the-world-seed-data'
    profiles: ["seed"]
    depends_on:
      vote:
        condition: service_healthy
    restart: "no"
    networks:
      - "front-tier"

volumes:
  vote-data:
  db-data:

networks:
  front-tier:
  back-tier:
